config/routes.rb
TaskManager::Application.routes.draw do

  resources :todolists do
        put '/tasks/:id' => 'tasks#update_title'
        put '/tasks/:id/status' => 'tasks#update_status'
        resources :tasks
  end

  root :to => 'todolists#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :todolist
  attr_accessible :deadline, :isDone, :title
  validates :title, presence: true,
            length: { minimum: 1 }
end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  attr_accessible :title
  validates :title, presence: true,
            length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, :if => Proc.new { |c| c.request.format == 'application/json' }

  skip_before_filter :verify_authenticity_token, :only => [:update]
  after_filter :cors_set_access_control_headers

# For all responses in this controller, return the CORS access control headers.

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, PATCH, DELETE, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = %w{Origin Accept Content-Type X-Requested-With auth_token X-CSRF-Token}.join(',')
    headers['Access-Control-Max-Age'] = "1728000"
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @todolist = Todolist.find(params[:todolist_id])
    @task = @todolist.tasks.create(task_params)
    respond_to do |format|
      format.html
      format.xml  { render :xml => @task}
      format.js
    end
  end

  def destroy
    @todolist = Todolist.find(params[:todolist_id])
    @task = @todolist.tasks.find(params[:id])
    @task_id = params[:id];
    @task.destroy
    respond_to do |format|
      if @task.save
          format.html {redirect_to(@task)}
          format.xml  { render :xml => @task }
          format.js
      else
          format.html {redirect_to(@task)}
          format.xml  { render :xml => task.errors, :status => :unprocessable_entity }
          format.js
      end
    end
  end

  def update_title
    @todolist = Todolist.find(params[:todolist_id])
    @task = @todolist.tasks.find(params[:id])
    @task.update_column('title', params[:title])
    render json: @task

  end

  def update_status
    @todolist = Todolist.find(params[:todolist_id])
    @task = @todolist.tasks.find(params[:id])
    @task.update_column('isDone', params[:status])
    render json: @task

  end

  private
  def task_params
    params.require(:task).permit(:title)
  end


end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def index
    @todolists = Todolist.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @todolists }
    end
  end

  def new
    @todolist = Todolist.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @todolist }
    end
  end

  def create
    @todolist = Todolist.new(params[:todolist])

    respond_to do |format|
      if @todolist.save
        format.html { redirect_to(@todolist, :notice => 'Todolist was successfully created.') }
        format.xml  { render :xml => @todolist, :status => :created, :location => @todolist }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @todolist.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @todolist = Todolist.find(params[:id])
    @todolist.destroy
    respond_to do |format|
      format.html {redirect_to(@todolist)}
      format.xml  { render :xml => @todolist }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", 'jquery-ui'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<div id="task_panel">
    <%= form_for([todolist, todolist.tasks.build], :remote => true) do |f| %>
      <div id="left_task_block">
        <%= image_tag("add_task_img.jpg")  %>
      </div>
      <div id="center_task_block">
        <%= f.text_field :title, :placeholder => 'Start typing here to create a task...', :class => 'task_type' %>
      </div>
      <div id="right_task_block">
        <%= image_submit_tag('add_task_btn.jpg')  %>
      </div>

    <% end %>
</div>

app/views/tasks/_task.html.erb
<% if task.id != nil %>

    <tr id="task_<%= task.id %>"  style="text-align: center" class="bottom_line">
      <td class="decor_td">
        <% if task.isDone %>
            <input type="checkbox" data-task-id="<%= task.id %>" data-todolist-id="<%= task.todolist.id %>" checked>
        <% else %>
            <input type="checkbox" data-task-id="<%= task.id %>" data-todolist-id="<%= task.todolist.id %>">
        <% end %>
      </td>

      <td id="task_<%= task.id %>_title" class="decor_td_2">
        <div id="persent_task_title_<%= task.id %>">
          <% if task.isDone %>
              <strike> <%= task.title %> </strike>
          <% else %>
              <%= task.title %>
          <% end %>

        </div>
        <div id="new_task_title_<%= task.id %>" style="display: none">
          <input type="text" id="new_title_<%= task.id %>">
        </div>
      </td>

      <td style="text-align: center; vertical-align: middle;  width: 55px">
        <div id="icons" style="display:none">
          <a href="#" data-task-id="<%= task.id %>" data-todolist-id="<%= task.todolist.id %>"><i class="icon-edit"></i>
          </a>

          <%= link_to "<i class='icon-trash'></i>".html_safe, todolist_task_path(task.todolist, task),
                      method: :delete, remote: true,
                      data: {confirm: 'Are you sure?'} %>
        </div>
      </td>
    </tr>

<% end %>

app/views/tasks/create.js.erb
<%- if @task.errors.any? %>
console.log('Error');

$("<div id='error_explanation'> Title can't be blank </div>").dialog();

<%- else %>
console.log('Created');
$("#tasks_"+ <%= @todolist.id %>).find('tbody').append('<%= escape_javascript(render(@task)) %>')

<% end %>

app/views/tasks/destroy.js.erb
console.log('Deleted');
$('#task_'+<%= @task.id %>).fadeOut();

app/views/todolists/_form.html.erb
<html>
<head>

</head>
<body>
<h1>New todolist</h1>

<%= form_for(@todolist, :remote => true) do |f| %>
    <% if @todolist.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

          <ul>
            <% @todolist.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

</body>
</html>

app/views/todolists/_todolist.html.erb
<%= div_for(todolist, class: "todolist-border") do %>
    <table  cellSpacing="0" cellPadding="0">
      <tr>

        <td>
          <div class="header">

            <div class="header_title"> <h3><font  color="#f5f5f5"><%= todolist.title %></font></h3>
            </div>

            <div class="header_trash">
              <%= link_to "<i class='icon-trash icon-white'></i>".html_safe, todolist_path(todolist),
                          method: :delete, data: {confirm: 'Are you sure?'}, remote: true %>
            </div>

          </div>

        </td>

      </tr>
      <tr>
        <td><%= render :partial => "tasks/form", locals: {todolist: todolist} %></td>
      </tr>
      <tr>
        <td>
          <div id="tasks_<%= todolist.id %>">


            <table id="tasks_<%= todolist.id %>" class="table table-condensed">

              <% if todolist.tasks.count() !=0 %>
                  <%= render todolist.tasks %>

              <% else %>
                  <tbody>

                  </tbody>
              <% end %>
            </table>
          </div>
        </td>
      </tr>
    </table>
<% end %>
<div id="indent_<%= todolist.id %>">
<br/>
</div>

app/views/todolists/create.js.erb
<%- if @todolist.errors.any? %>
  console.log('Error');
  $('#dialog-form').html('<%= escape_javascript(render('form')) %>');
<%- else %>
  console.log('Created');
  $('#dialog-form').dialog('close');
  $('#dialog-form').remove();
  $('#todolists').append('<%= escape_javascript(render(@todolist)) %>');
<%- end %>

app/views/todolists/destroy.js.erb
console.log('Deleted');
$('#todolist_'+<%= @todolist.id %>).fadeOut();
$('#indent_'+<%= @todolist.id %>).fadeOut();

app/views/todolists/index.html.erb
<html>
<head>

</head>
<body id="bg_image">
<div class="my_container">

  <p>

  <h3>SIMPLE TODO LISTS</h3>

  FOR RUBY GARAGE

  <br/><br/>

  <div class="main">
    <div id="todolists" class="main">
      <%= render :partial => @todolists %>
    </div>

    <br/>
    <%= link_to image_tag('add_todo_btn.jpg'), new_todolist_path, :id => 'create_todolist' %>
  </div>
</div>

<div class="footer">
  &copy arakorno
</div>

</body>
</html>

app/views/todolists/new.html.erb
<html>
<head>
</head>
<body>

<div id="content">

  <%= render 'form' %>

</div>



</body>
</html>